[package]
name = "rustest"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["rustest_core", "tests"]

[workspace.dependencies]
rustest_core = { path = "rustest_core" }

[dependencies]
rustest_core.workspace = true